.TH "/home/travis/build/bwachter/ibaard/src/ibaard_platform.h" 3 "Thu Nov 15 2018" "ibaard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/bwachter/ibaard/src/ibaard_platform.h \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Define common macros for different compilers 
.PP
Definition in file \fBibaard_platform\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ibaard from the source code\&.
