.TH "/home/travis/build/bwachter/ibaard/src/ibaard_getopt.h" 3 "Thu Nov 15 2018" "ibaard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/bwachter/ibaard/src/ibaard_getopt.h \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
getopt() ripped out of dietlibc for use in win32 and other environments not providing getopt() 
.PP
Definition in file \fBibaard_getopt\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ibaard from the source code\&.
