.TH "/home/travis/build/bwachter/ibaard/src/shell.c" 3 "Thu Nov 15 2018" "ibaard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/bwachter/ibaard/src/shell.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <sys/param\&.h>\fP
.br
\fC#include <sys/mount\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <sys/reboot\&.h>\fP
.br
\fC#include 'ibaard_shell\&.h'\fP
.br
\fC#include 'ibaard_types\&.h'\fP
.br
\fC#include 'ibaard_log\&.h'\fP
.br
\fC#include 'ibaard_fs\&.h'\fP
.br
\fC#include 'ibaard\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBO_LARGEFILE\fP   0100000"
.br
.RI "\fICompat definition for broken platforms\&. \fP"
.ti -1c
.RI "#define \fBMS_MGC_VAL\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBash_init\fP (char *info)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBfancyprompt\fP"
.br
.ti -1c
.RI "} \fBash_settings\fP"
.br
.RI "\fIStore runtime settings of the shell\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Bernd Wachter bwachter@lart.info 
.RE
.PP
\fBDate:\fP
.RS 4
2005-2011 
.RE
.PP

.PP
Definition in file \fBshell\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int ash_init (char *info)"
Initialize a minimalistic rescue shell
.PP
\fBParameters:\fP
.RS 4
\fIinfo\fP a message to display on shell launch 
.RE
.PP
\fBReturns:\fP
.RS 4
always returns 0 
.RE
.PP

.PP
Definition at line 413 of file shell\&.c\&.
.PP
.nf
413                         {
414   char buf[512];
415 
416   emsg(info, 0);
417   ash_settings\&.fancyprompt=0;
418 
419   while(strcmp(buf,"exit")){
420     if (ash_settings\&.fancyprompt)
421       lmsg(xgetcwd(buf), "> ", 0);
422     else
423       lmsg("> ", 0);
424     ash_read(buf);
425     ash_shellcmd(buf);
426   }
427   return 0;
428 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for ibaard from the source code\&.
